name: Bump Version
on:
  push:
    tags:
      - 'v*'

jobs:
  bump-version:
    name: Bump version in pubspec.yaml
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Calculate and update version
        working-directory: ./app
        id: calc_and_update
        run: |
          NEW_VERSION_NAME=$(echo ${{ github.ref_name }} | sed 's/^v//')
          NEW_VERSION_CODE=$(awk -F '[+]' '/version:/ {print $2 + 1}' ./pubspec.yaml)
          NEW_VERSION=$NEW_VERSION_NAME+$NEW_VERSION_CODE
          sed -i "s/^version: .*/version: $NEW_VERSION/" pubspec.yaml
          echo "new_version=$NEW_VERSION" >> GITHUB_OUTPUT
      - name: Commit and push changes
        working-directory: ./app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add ./pubspec.yaml
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m 'chore: bump version to `${{ steps.calc_and_update.new_version }}`'
          git push

