name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    outputs:
      version: ${{ steps.release.outputs.release_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Install semantic-release tools
        run: |
          npm install -g \
          @semantic-release/commit-analyzer \
          @semantic-release/release-notes-generator \
          @semantic-release/github \
          semantic-release
      - name: Release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release --branches main --plugins "@semantic-release/commit-analyzer,@semantic-release/release-notes-generator,@semantic-release/github"
          VERSION=$(git describe --tags --abbrev=0)
          echo "release_version=$VERSION" >> $GITHUB_OUTPUT

  build-app:
    name: Build App (${{ matrix.os }})
    needs: release
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    if: needs.release.result == 'success'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v6
      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Set app version (Linux/Windows)
        working-directory: ./app
        if: runner.os != 'macOS'
        shell: bash
        run: |
          VERSION=$(echo "${{ needs.release.outputs.version }}" | sed 's/^v//' | sed 's/[+-].*//')
          echo "VERSION_NAME=$VERSION" >> $GITHUB_ENV
          MAJOR=$(echo $VERSION | cut -d '.' -f1)
          MINOR=$(echo $VERSION | cut -d '.' -f2)
          PATCH=$(echo $VERSION | cut -d '.' -f3)
          VERSION_CODE=$((MAJOR * 100000000 + MINOR * 10000 + PATCH))
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV
          VERSION="$VERSION+$VERSION_CODE"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          sed -i "s/^version: .*/version: $VERSION/" pubspec.yaml
      - name: Set app version (macOS)
        working-directory: ./app
        if: runner.os == 'macOS'
        run: |
          VERSION=$(echo "${{ needs.release.outputs.version }}" | sed 's/^v//' | sed 's/[+-].*//')
          echo "VERSION_NAME=$VERSION" >> $GITHUB_ENV
          MAJOR=$(echo $VERSION | cut -d '.' -f1)
          MINOR=$(echo $VERSION | cut -d '.' -f2)
          PATCH=$(echo $VERSION | cut -d '.' -f3)
          VERSION_CODE=$((MAJOR * 100000000 + MINOR * 10000 + PATCH))
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV
          VERSION="$VERSION+$VERSION_CODE"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          sed -i '' "s/^version: .*/version: $VERSION/" pubspec.yaml

      - name: Get Flutter packages
        working-directory: ./app
        shell: bash
        run: flutter pub get

      - name: Build for Android
        working-directory: ./app
        if: runner.os == 'Linux'
        run: |
          CODE_ARM64=$((${{ env.VERSION_CODE }} * 10 + 1))
          CODE_ARM32=$((${{ env.VERSION_CODE }} * 10 + 2))
          CODE_X86_64=$((${{ env.VERSION_CODE }} * 10 + 3))

          echo "CODE_ARM64=$CODE_ARM64" >> $GITHUB_ENV
          echo "CODE_ARM32=$CODE_ARM32" >> $GITHUB_ENV
          echo "CODE_X86_64=$CODE_X86_64" >> $GITHUB_ENV

          flutter build apk --release --target-platform android-arm64 --build-name=${{ env.VERSION_NAME }} --build-number=$CODE_ARM64
          flutter build apk --release --target-platform android-arm --build-name=${{ env.VERSION_NAME }} --build-number=$CODE_ARM32
          flutter build apk --release --target-platform android-x64 --build-name=${{ env.VERSION_NAME }} --build-number=$CODE_X86_64
          flutter build appbundle --release
          mv build/app/outputs/flutter-apk/app-arm64-v8a-release.apk push_through-${{ env.VERSION_NAME }}+$CODE_ARM64-android-arm64-v8a.apk
          mv build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk push_through-${{ env.VERSION_NAME }}+$CODE_ARM32-android-armeabi-v7a.apk
          mv build/app/outputs/flutter-apk/app-x86_64-release.apk push_through-${{ env.VERSION_NAME }}+$CODE_X86_64-android-x86_64.apk
          mv build/app/outputs/bundle/release/app-release.aab push_through-${{ env.VERSION }}-android.aab
      - name: Upload Android binaries
        if: runner.os == 'Linux'
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ needs.release.outputs.version }}
          files: |
            app/push_through-${{ env.VERSION_NAME }}+${{ env.CODE_ARM64 }}-android-arm64-v8a.apk
            app/push_through-${{ env.VERSION_NAME }}+${{ env.CODE_ARM32 }}-android-armeabi-v7a.apk
            app/push_through-${{ env.VERSION_NAME }}+${{ env.CODE_X86_64 }}-android-x86_64.apk
            app/push_through-${{ env.VERSION }}-android.aab
          overwrite_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build for iOS
        working-directory: ./app
        if: runner.os == 'macOS'
        run: flutter build ios --release --no-codesign --build-name=${{ env.VERSION_NAME }} --build-number=${{ env.VERSION_CODE }}
      - name: Zip iOS binaries
        if: runner.os == 'macOS'
        working-directory: ./app
        run: |
          cd build/ios/iphoneos/Runner.app
          zip -r ../../../../push_through-${{ env.VERSION }}-ios.zip *
      - name: Upload iOS binaries
        if: runner.os == 'macOS'
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ needs.release.outputs.version }}
          files: app/push_through-${{ env.VERSION }}-ios.zip
          overwrite_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build for Linux
        working-directory: ./app
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build libgtk-3-dev
          flutter build linux
      - name: Zip Linux binaries
        if: runner.os == 'Linux'
        working-directory: ./app
        run: |
          cd build/linux/x64/release/bundle
          zip -r ../../../../../push_through-${{ needs.release.outputs.version }}-linux-x86_64-portable.zip *
      - name: Upload Linux binaries
        if: runner.os == 'Linux'
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ needs.release.outputs.version }}
          files: app/push_through-${{ needs.release.outputs.version }}-linux-x86_64-portable.zip
          overwrite_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build for Windows
        working-directory: ./app
        shell: bash
        if: runner.os == 'Windows'
        run: flutter build windows
      - name: Zip Windows binaries
        if: runner.os == 'Windows'
        working-directory: ./app
        shell: pwsh
        run: Compress-Archive -Path build/windows/x64/runner/Release/* -DestinationPath push_through-${{ needs.release.outputs.version }}-windows-x86_64-portable.zip
      - name: Upload Windows binaries
        if: runner.os == 'Windows'
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ needs.release.outputs.version }}
          files: app/push_through-${{ needs.release.outputs.version }}-windows-x86_64-portable.zip
          overwrite_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build for macOS
        working-directory: ./app
        if: runner.os == 'macOS'
        run: flutter build macos
      - name: Zip macOS binaries
        if: runner.os == 'macOS'
        working-directory: ./app
        run: |
          cd build/macos/Build/Products/Release/push_through.app/
          zip -r ../../../../../../push_through-${{ needs.release.outputs.version }}-macos-x86_64.zip *
      - name: Upload macOS binaries
        if: runner.os == 'macOS'
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ needs.release.outputs.version }}
          files: app/push_through-${{ needs.release.outputs.version }}-macos-x86_64.zip
          overwrite_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

